#!/bin/bash
# --------------------------- ALIASES
alias ls='ls --color=auto'
alias ls="ls --color"
alias grep="grep --color"
alias ll="ls -lh"
alias reboot="sudo reboot"
alias shutdown="sudo shutdown"

alias pacman="sudo pacman"
alias aura="sudo aura"
alias orphans="pacman -Qtdq" # packages not required by any other
alias expliciti="pacman -Qetq" # explicitly installed packages not required by any other
alias mplayer='mplayer -vsync'
alias pdf='zathura'
alias rawvim="vim -u ~/.rawvim"

# --------------------------- EXPORTS
export PYTHONPATH=$PYTHONPATH:/usr/lib/python3.5/site-packages/:~/.local/lib/python3.5/site-packages:/usr/lib/python3.6/site-packages/:~/.local/lib/python3.6/site-packages
export XDG_CONFIG_HOME=~/.config/
export POWERLINE_ROOT=~/.local/lib/python3.6/site-packages/powerline
export PATH=~/bin:$PATH
export EDITOR=nvim

# --------------------------- COLORED MAN PAGES
man() {
    env LESS_TERMCAP_mb=$'\E[01;31m' \
                        LESS_TERMCAP_md=$'\E[01;38;5;74m' \
                        LESS_TERMCAP_me=$'\E[0m' \
                        LESS_TERMCAP_se=$'\E[0m' \
                        LESS_TERMCAP_so=$'\E[31;31m' \
                        LESS_TERMCAP_ue=$'\E[0m' \
                        LESS_TERMCAP_us=$'\E[04;38;5;146m' \
                        man "$@"
}
# --------------------------- FUNCTIONS
# top 15 most used commands
topfifteen() {
	history | awk '{if ($4 == "sudo") {print $5} else {print $4}}' | \
		awk 'BEGIN {FS ="|"} {print $1}' \
		| grep -v topfifteen | sort | uniq -c | sort -rn | head -15
}

# Aura sudo for build
function a(){
    AURA="$(aura "$@")"
    if echo "$AURA" | grep -q '^aura >>= .*You have to use `.*sudo.*` for that.*$'
    then
        sudo aura "$@"
    else
        echo "$AURA"
    fi
}
