#!/bin/bash
#--------------------------- ALIASES
alias ls='ls --color=auto'
alias ls="ls --color"
alias grep="grep --color"
alias ll="ls -l"
alias reboot="sudo reboot"
alias shutdown="sudo shutdown"

alias pacman="sudo pacman"
alias aura="sudo aura"
#--------------------------- EXPORTS
export POWERLINE_ROOT="/home/adi/.local/lib/python3.5/site-packages/powerline"
export PYTHONPATH=$PYTHONPATH:/usr/lib/python3.5/site-packages/:~/.local/lib/python3.5/site-packages
export XDG_CONFIG_HOME=~/.config/

#--------------------------- COLORED MAN PAGES
man() {
    env LESS_TERMCAP_mb=$'\E[01;31m' \
                        LESS_TERMCAP_md=$'\E[01;38;5;74m' \
                        LESS_TERMCAP_me=$'\E[0m' \
                        LESS_TERMCAP_se=$'\E[0m' \
                        LESS_TERMCAP_so=$'\E[31;31m' \
                        LESS_TERMCAP_ue=$'\E[0m' \
                        LESS_TERMCAP_us=$'\E[04;38;5;146m' \
                        man "$@"
}
